name: Update Submodule on Dispatch

on:
  repository_dispatch:
    types: [submodule_updated]

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository with submodules
      - name: Checkout repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive  # Fetch all submodules recursively

      # Step 2: Set up Git user for committing changes
      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Step 3: Update all submodules to their latest commits
      - name: Update submodules to latest commit
        run: |
          git submodule update --remote --merge

      # Step 4: Commit the updated submodules if there are any changes
      - name: Commit changes if submodules are updated
        run: |
          git add .
          git commit -m "Update all submodules to latest commit" || echo "No changes to commit"

      # Step 5: Push changes back to the repository
      - name: Push changes to repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the GITHUB_TOKEN for authentication
        run: |
          git push origin HEAD:main  # Replace 'main' with the branch you are working on
